export const servicesItems = [
  {
    id: "tech",
    image: "/services/tech.svg",
    title: "Latest and Greatest Tech",
    alt: "tech",
    width: 40,
    height: 33.63,
    moWidth: 24.97,
    moHeight: 21,
  },
  {
    id: "guarantee",
    image: "/services/guarantee.svg",
    title: "Guarantee",
    alt: "guarantee",
    width: 40,
    height: 43.77,
    moWidth: 24.67,
    moHeight: 27,
  },
  {
    id: "shipping",
    image: "/services/shipping.svg",
    title: "Free Shipping over 1000$",
    alt: "shipping",
    width: 62,
    height: 30.56,
    moWidth: 32.46,
    moHeight: 16,
  },
  {
    id: "support",
    image: "/services/support.svg",
    title: "24/7 Support",
    alt: "support",
    width: 40,
    height: 45.02,
    moWidth: 24,
    moHeight: 27,
  },
];
