import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar/Navbar";
import { Toaster } from "sonner";
import FooterWrapper from "@/components/layout/footer/FooterWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white overflow-x-hidden`}>
        <div className="mx-auto flex min-h-screen w-full min-w-0 flex-col">
          <Navbar />

          <div className="hidden md:block h-px w-full bg-linear-to-r from-[#0C68F4]/30 via-[#0C68F4]/70 to-[#0C68F4]/30" />

          <main className="mx-auto w-full min-w-0 max-w-full flex-1 px-6 sm:px-14.5 md:px-19.5 lg:px-24 xl:px-27 sm:max-w-3xl md:max-w-5xl lg:max-w-7xl xl:max-w-360">
            {children}
          </main>

          <Toaster
            position="bottom-right"
            richColors
            style={{
              right: "110px",
            }}
            toastOptions={{
              style: {
                width: "312px",
              },
            }}
          />

          <FooterWrapper />
        </div>
      </body>
    </html>
  );
}
