import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-full min-h-screen mx-auto bg-white`}
      >
        <Navbar />
        <div className="hidden sm:block w-full z-100 h-px bg-linear-to-r from-[#0C68F4]/30 via-[#0C68F4]/70 to-[#0C68F4]/30 scale-x-100" />
        <div className="mx-auto flex min-h-screen w-full flex-col px-6 sm:px-14.5 md:px-19.5 lg:px-24 xl:px-27 sm:max-w-3xl md:max-w-5xl lg:max-w-7xl xl:max-w-360">
          <main className="flex-1">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
