import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} bg-white overflow-x-hidden`}>
      <body className="min-h-screen flex flex-col">
        {children}
        <Toaster
          position="bottom-right"
          richColors
          style={{
            right: "110px",
          }}
          toastOptions={{
            style: {
              width: "312px",
            },
          }}
        />
      </body>
    </html>
  );
}
